# Generated by Django 5.2 on 2024-06-08

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the note', max_length=255)),
                ('content', models.TextField(help_text='The detailed content of the note')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the note was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the note was last updated')),
                ('owner', models.ForeignKey(help_text='User who owns this note', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
